join-com/cal-com

apps/web/components/getting-started/steps-views/ConnectCalendars.tsx, apps/web/components/getting-started/steps-views/SetupAvailability.tsx, apps/web/pages/getting-started/[[...step]].tsx, packages/ui/components/form/step/Steps.tsx
[JOIN-27734]
[JOIN-27734]: https://joinsolutionsag.atlassian.net/browse/JOIN-27734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: JOIN-27734 update registration flow and integration

apps/web/components/ui/AuthContainer.tsx, apps/web/pages/auth/login.tsx
[Join-27735](https://joinsolutionsag.atlassian.net/browse/JOIN-27735)
=> feat: Join-27735 update login page

apps/web/components/getting-started/steps-views/SetupAvailability.tsx, apps/web/public/static/locales/en/common.json, packages/features/shell/Shell.tsx, packages/lib/defaultEvents.ts
[JOIN-28998] [JOIN-29001]
[JOIN-28998]: https://joinsolutionsag.atlassian.net/browse/JOIN-28998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JOIN-29001]: https://joinsolutionsag.atlassian.net/browse/JOIN-29001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: JOIN-28998 JOIN-29001 account setup

apps/web/components/getting-started/steps-views/SetupAvailability.tsx
=> fix: TECH setup page workaround

apps/web/components/getting-started/steps-views/SetupAvailability.tsx
=> fix: TECH setup page

apps/web/pages/auth/admin-login.tsx, apps/web/pages/auth/login.tsx, packages/features/shell/Shell.tsx, yarn.lock
=> feat: TECH add admin login page and add settings page

packages/features/shell/Shell.tsx
=> link update

apps/web/components/auth/layouts/AdminLayout.tsx, packages/features/settings/layouts/SettingsLayout.tsx, packages/features/shell/Shell.tsx
=> feat: JOIN-28327 setup admin role

apps/web/public/static/locales/de/common.json, apps/web/public/static/locales/en/common.json, apps/web/public/static/locales/es/common.json, apps/web/public/static/locales/fr/common.json, apps/web/public/static/locales/it/common.json, apps/web/public/static/locales/nl/common.json
=> feat: JOIN-28777 add translations

apps/web/components/getting-started/steps-views/SetupAvailability.tsx, apps/web/pages/getting-started/[[...step]].tsx, packages/features/shell/Shell.tsx
=> fix: JOIN-29006 possibility to skip availability

apps/web/pages/event-types/index.tsx, packages/config/tailwind-join-preset.js, packages/features/eventtypes/components/Banner.tsx, packages/features/shell/Shell.tsx
=> feat: JOIN-29382 onboarding banner

apps/web/pages/auth/admin-login.tsx
=> fix login-admin

apps/web/pages/auth/admin-login.tsx
=> fix admin login

apps/web/components/getting-started/steps-views/SetupAvailability.tsx
=> fix: JOIN-27575 onboarding process

apps/web/components/apps/App.tsx, apps/web/pages/apps/[slug]/index.tsx
[JOIN-29505] [JOIN-29527]
[JOIN-29505]: https://joinsolutionsag.atlassian.net/browse/JOIN-29505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JOIN-29527]: https://joinsolutionsag.atlassian.net/browse/JOIN-29527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: JOIN-29505 JOIN-29527 rebranding

apps/web/components/auth/layouts/AdminLayout.tsx, packages/features/shell/Shell.tsx
=> fix: TECH add inactive admin

apps/web/public/static/locales/de/common.json, apps/web/public/static/locales/en/common.json, apps/web/public/static/locales/es/common.json, apps/web/public/static/locales/fr/common.json, apps/web/public/static/locales/it/common.json, apps/web/public/static/locales/nl/common.json, packages/features/eventtypes/components/CreateEventTypeDialog.tsx
[JOIN-29021]
Before:
After:
[JOIN-29021]: https://joinsolutionsag.atlassian.net/browse/JOIN-29021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: JOIN-29021 cahnge duplicate url error text

apps/web/components/auth/layouts/AdminLayout.tsx
=> fix is admin

apps/web/components/apps/App.tsx
=> feat: TECH remove report app section

apps/web/pages/auth/login.tsx, packages/app-store/apps.browser.generated.tsx, packages/app-store/apps.keys-schemas.generated.ts, packages/app-store/apps.metadata.generated.ts, packages/app-store/apps.schemas.generated.ts
[JOIN-29724]
After user visit `login/auth` page then there will be an attempt to login user automatically.
https://user-images.githubusercontent.com/110449633/228224181-3eeb2cb2-9782-4c90-869d-325642013552.mov
[JOIN-29724]: https://joinsolutionsag.atlassian.net/browse/JOIN-29724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: JOIN-29724 auto login

apps/web/components/booking/BookingListItem.tsx, packages/app-store/apps.browser.generated.tsx, packages/app-store/apps.keys-schemas.generated.ts, packages/app-store/apps.metadata.generated.ts, packages/app-store/apps.schemas.generated.ts
[JOIN-29753]
Before:
After:
[JOIN-29753]: https://joinsolutionsag.atlassian.net/browse/JOIN-29753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: JOIN-29753 remove request reschedule btn

apps/web/components/getting-started/steps-views/SetupAvailability.tsx, apps/web/components/ui/PoweredByCal.tsx, packages/features/shell/Shell.tsx
=> fix: JOIN-29803 create default events with correct config, remove cal.com branding

apps/web/next.config.js
[JOIN-29859]
[JOIN-29859]: https://joinsolutionsag.atlassian.net/browse/JOIN-29859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: JOIN-29859 add auto redirects from logout to eventTypes

packages/prisma/seed-app-store.ts
- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- I haven't checked if …
=> Prevent updating app to enabled on seed app store

apps/web/components/getting-started/components/ConferenceAppItem.tsx, apps/web/components/getting-started/steps-views/ConnectConferenceApps.tsx, apps/web/pages/getting-started/[[...step]].tsx, apps/web/public/static/locales/de/common.json, apps/web/public/static/locales/en/common.json, apps/web/public/static/locales/es/common.json, apps/web/public/static/locales/fr/common.json, apps/web/public/static/locales/it/common.json, apps/web/public/static/locales/nl/common.json, packages/app-store/components.tsx, packages/app-store/googlevideo/api/_getAdd.ts, packages/app-store/office365video/api/callback.ts, packages/app-store/zoomvideo/api/callback.ts, packages/features/auth/lib/next-auth-options.ts, packages/types/next-auth.d.ts
[JOIN-30105]
[JOIN-30105]: https://joinsolutionsag.atlassian.net/browse/JOIN-30105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: JOIN-30105 add conference apps onboarding step

packages/app-store/applecalendar/api/add.ts, packages/app-store/exchange2013calendar/api/add.ts, packages/app-store/exchange2016calendar/api/add.ts, packages/app-store/exchangecalendar/api/_postAdd.ts
- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- I haven't checked if …
=> fix: JOIN-34405 extending catch logic to return authentication error
